source 'https://github.com/CocoaPods/Specs.git'        #官方仓库地址

use_frameworks!

platform :ios, '10.0'

target 'YZJPracticeSDK_Example' do
  pod 'YZJPracticeSDK', :path => '../'

  target 'YZJPracticeSDK_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
